title: CCI.io
description: Cancer Care Informatics - Prompt Engineering Course
theme: minima
url: "https://IyadSultan.github.io"
baseurl: "/CCI.io"

header_pages: []

exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - "Session 1/notebookLM.txt"
  - "Session 2/session_2_curriculum.md"
  - "Session 3/session_3_curriculum.md"
  - "session_4/session_4_curriculum.md"
  - "Session 5"
  - "Session 2/practices/practice_lesson6_wrapup_review.md"
  - "Session 2/quizzes/quiz_lesson6_wrapup_selfcheck.md"
  - "session_5/practices/*.jsx"
  - "session_5/quizzes/*.jsx"
