#!/usr/bin/env bash
# Shared settings for the CCI Session 12 hardened-VM lab.
# Every numbered script sources this file, so you change a name in ONE place.
# These run in Azure Cloud Shell (https://shell.azure.com) — the `az` tool is
# already installed and already logged in. Nothing is installed on your laptop.

# The one box that holds everything — deleting it (script 99) erases the whole lab.
export RG="cci-hardening-lab"

# A nearby Azure region. (Run `az account list-locations -o table` to see options.)
export LOCATION="uaenorth"

# The virtual machine.
export VM="cci-web"
export VM_IMAGE="Ubuntu2204"        # a current, PATCHED Linux image (Lesson 4: patch known holes)
export VM_SIZE="Standard_B1s"       # tiny + cheap; fine for one web page
export ADMIN_USER="azureuser"       # a NON-root, least-privilege login (Lesson 5)

# Azure names the auto-created network security group "<vm>NSG".
export NSG="${VM}NSG"

# NO SECRETS LIVE IN THIS FILE. The SSH key is generated by `az vm create
# --generate-ssh-keys` and stays in Cloud Shell — it is never typed or stored here.
