import React, { useState } from 'react';

const files = [
  { name: "README.md", commit: true, reason: "Documents what the project does and how to run it. Always committed." },
  { name: ".env", commit: false, reason: "Contains real secrets (API keys). NEVER committed. Listed in .gitignore." },
  { name: ".env.example", commit: true, reason: "Documents which environment variables exist, with placeholder values. Committed so colleagues know what to fill in." },
  { name: "drugs.db", commit: false, reason: "SQLite database file. For our toy project the data is non-sensitive, but the general rule is: databases may contain real or sample PHI — exclude by default, regenerate from init_db.py." },
  { name: ".gitignore", commit: true, reason: "The exclusion list itself IS committed — it is the public contract of what this project does not share." },
  { name: "app.py", commit: true, reason: "Your application source code. This is the whole point of the repo. Always committed." },
  { name: ".venv/", commit: false, reason: "Hundreds of MB of installed packages. Regenerated by pip install -r requirements.txt. Never committed." },
  { name: "patient_data.csv", commit: false, reason: "Patient identifiers — even sample data named this way is a red flag. Never committed, full stop. PHI does not belong in git." }
];

export default function Practice() {
  const [choices, setChoices] = useState({});
  const [submitted, setSubmitted] = useState(false);

  const choose = (name, val) => {
    if (submitted) return;
    setChoices({ ...choices, [name]: val });
  };

  const check = () => setSubmitted(true);
  const reset = () => { setChoices({}); setSubmitted(false); };

  const score = files.filter(f => choices[f.name] === f.commit).length;
  const answeredCount = Object.keys(choices).length;

  return (
    <div style={{ maxWidth: 760, margin: '40px auto', fontFamily: 'system-ui' }}>
      <h3>Should This File Be Committed?</h3>
      <p style={{ background: '#f8f9fa', padding: 16, borderRadius: 8, lineHeight: 1.6 }}>
        For each file, decide: should this go into git (committed and pushed to GitHub) or NOT (listed in .gitignore)?
      </p>

      {files.map((f) => {
        const userChoice = choices[f.name];
        const correct = submitted && userChoice === f.commit;
        const wrong = submitted && userChoice !== undefined && userChoice !== f.commit;
        return (
          <div key={f.name} style={{
            padding: '12px 16px', margin: '8px 0', borderRadius: 8,
            border: `2px solid ${correct ? '#198754' : wrong ? '#dc3545' : '#dee2e6'}`,
            background: correct ? '#d4edda' : wrong ? '#f8d7da' : '#fff'
          }}>
            <div style={{ display: 'flex', alignItems: 'center' }}>
              <code style={{ flex: 1, fontFamily: 'monospace', fontSize: 15, fontWeight: 'bold' }}>{f.name}</code>
              <button onClick={() => choose(f.name, true)} disabled={submitted} style={{
                marginLeft: 8, padding: '6px 14px', borderRadius: 6, cursor: submitted ? 'default' : 'pointer',
                border: `2px solid ${userChoice === true ? '#198754' : '#ccc'}`,
                background: userChoice === true ? '#198754' : '#fff', color: userChoice === true ? '#fff' : '#000'
              }}>Commit</button>
              <button onClick={() => choose(f.name, false)} disabled={submitted} style={{
                marginLeft: 8, padding: '6px 14px', borderRadius: 6, cursor: submitted ? 'default' : 'pointer',
                border: `2px solid ${userChoice === false ? '#dc3545' : '#ccc'}`,
                background: userChoice === false ? '#dc3545' : '#fff', color: userChoice === false ? '#fff' : '#000'
              }}>Don't Commit</button>
            </div>
            {submitted && (
              <p style={{ marginTop: 8, marginBottom: 0, fontSize: 14, color: '#333' }}>
                <strong>{f.commit ? "Commit" : "Don't commit"}.</strong> {f.reason}
              </p>
            )}
          </div>
        );
      })}

      {!submitted && (
        <button onClick={check} disabled={answeredCount < files.length} style={{
          marginTop: 16, padding: '10px 24px', borderRadius: 6, border: 'none',
          background: '#198754', color: '#fff', cursor: answeredCount < files.length ? 'default' : 'pointer',
          opacity: answeredCount < files.length ? 0.5 : 1
        }}>Check My Choices ({answeredCount}/{files.length})</button>
      )}

      {submitted && (
        <div style={{ marginTop: 16, padding: 16, background: '#f0f4ff', borderRadius: 8, borderLeft: '4px solid #0d6efd' }}>
          <p><strong>Score: {score} / {files.length}</strong></p>
          <p>{score === files.length ? "Perfect — you have the secrets mindset." : score >= 6 ? "Good — but review the misses. In clinical work, even one wrong call can leak PHI or an API key." : "Review the lesson. This is the highest-stakes habit of the session."}</p>
          <button onClick={reset} style={{ marginTop: 12, padding: '10px 24px', borderRadius: 6, border: 'none', background: '#0d6efd', color: '#fff', cursor: 'pointer' }}>Try Again</button>
        </div>
      )}
    </div>
  );
}
